### PR TITLE
Gpl config changes

### PR DESCRIPTION
**Pull request by GrrrD**
https://trello.com/c/clp92IqJ/103-2-display-unmatched-immunizations-below-table-view
https://trello.com/c/vqjqZeKm/108-1-remove-flu-from-pediatric-immunization-chart
https://trello.com/c/IbOPTCZD/101-1-ensure-ipv-polio-vaccine-is-displayed-in-immunization-chart

### CODE REVIEW

**Comment by eliotk** [comment]
:octocat: fantastic! 

would you mind updating the usage section in README (https://github.com/IoraHealth/pediatric-immunizations-schedule/blob/master/README.md#usage) w/ a little bit about using the new "append" call for rendering? oh also perhaps an addition about using the new unused object?

**Comment by GrrrD** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;clp92IqJ&#x2F;103-2-display-unmatched-immunizations-below-table-view"> (2) Display unmatched immunizations below table view</a>

**Comment by GrrrD** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vqjqZeKm&#x2F;108-1-remove-flu-from-pediatric-immunization-chart"> (1) Remove Flu from Pediatric Immunization chart</a>

**Comment by GrrrD** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IbOPTCZD&#x2F;101-1-ensure-ipv-polio-vaccine-is-displayed-in-immunization-chart"> (1) Ensure IPV (Polio) vaccine is displayed in immunization chart</a>

**Comment by eliotk** [comment]
:octocat:

**Pull request merged**
